version: '3.7'

services:
  db:
    image: postgres
    container_name: 'riper_user_postgres'
    env_file:
      - ./user-service/.env.prod
    volumes:
      - './bin/:/docker-entrypoint-initdb.d/'
    networks:
      - user-service

  gateway-service:
    build: ./gateway-service
    ports:
      - '8000:8000'
    env_file:
      - ./gateway-service/.env.prod
    networks:
      - all

  user-service:
    build: ./user-service
    env_file:
      - ./user-service/.env.prod
    networks:
      - all
      - user-service

  security-service:
    build: ./security-service
    env_file:
      - ./security-service/.env.prod
    networks:
      - all

networks:
  user-service:
    driver: bridge
  all:
    driver: bridge
